<a href="https://www.kaggle.com/code/raghavs21/home-loan-approval?scriptVersionId=133387506" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Importing the dataset**

In [2]:
dataset = pd.read_csv('/kaggle/input/home-loan-approval/loan_sanction_train.csv')

In [3]:
dataset.info


<bound method DataFrame.info of       Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849          

**Extracting categorical and numerical features**

In [4]:
columns_to_drop = ['Loan_ID', 'Dependents', 'Loan_Status']
numerical_features = dataset.drop(columns_to_drop, axis = 1).select_dtypes(include = ['number']).columns.tolist()
categorical_features = dataset.drop(columns_to_drop, axis = 1).select_dtypes(exclude = ['number']).columns.tolist()

**Handling the missing data**

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(dataset[numerical_features])
dataset[numerical_features] = imputer.transform(dataset[numerical_features])

In [6]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer.fit(dataset[categorical_features])
dataset[categorical_features] = imputer.transform(dataset[categorical_features])

In [7]:
dataset[categorical_features]

Gender Married     Education Self_Employed Property_Area
0      Male      No      Graduate            No         Urban
1      Male     Yes      Graduate            No         Rural
2      Male     Yes      Graduate           Yes         Urban
3      Male     Yes  Not Graduate            No         Urban
4      Male      No      Graduate            No         Urban
..      ...     ...           ...           ...           ...
609  Female      No      Graduate            No         Rural
610    Male     Yes      Graduate            No         Rural
611    Male     Yes      Graduate            No         Urban
612    Male     Yes      Graduate            No         Urban
613  Female      No      Graduate           Yes     Semiurban

[614 rows x 5 columns]

**Handling the categorical features**

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), categorical_features)], remainder = 'passthrough')
dataset = ct.fit_transform(dataset)

In [9]:
dataset[:,:]

array([[0.0, 1.0, 1.0, ..., 360.0, 1.0, 'Y'],
       [0.0, 1.0, 0.0, ..., 360.0, 1.0, 'N'],
       [0.0, 1.0, 0.0, ..., 360.0, 1.0, 'Y'],
       ...,
       [0.0, 1.0, 0.0, ..., 360.0, 1.0, 'Y'],
       [0.0, 1.0, 0.0, ..., 360.0, 1.0, 'Y'],
       [1.0, 0.0, 1.0, ..., 360.0, 0.0, 'N']], dtype=object)

In [10]:

# Convert the transformed dataset back to a DataFrame
transformed_df = pd.DataFrame(dataset)

# Print the first few rows of the transformed DataFrame
print(transformed_df.head())

    0    1    2    3    4    5    6    7    8    9    10        11 12      13  \
0  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  LP001002  0  5849.0   
1  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  LP001003  1  4583.0   
2  0.0  1.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  LP001005  0  3000.0   
3  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  LP001006  0  2583.0   
4  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  LP001008  0  6000.0   

       14          15     16   17 18  
0     0.0  146.412162  360.0  1.0  Y  
1  1508.0       128.0  360.0  1.0  N  
2     0.0        66.0  360.0  1.0  Y  
3  2358.0       120.0  360.0  1.0  Y  
4     0.0       141.0  360.0  1.0  Y  


**Extracting the dependent and independent features**

In [11]:
X = transformed_df.iloc[:, [0] + list(range(1, 11)) + list(range(13, transformed_df.shape[1]-1))].values
y = transformed_df.iloc[:, -1].values

In [12]:
X

array([[0.0, 1.0, 1.0, ..., 146.41216216216216, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 128.0, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 66.0, 360.0, 1.0],
       ...,
       [0.0, 1.0, 0.0, ..., 253.0, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 187.0, 360.0, 1.0],
       [1.0, 0.0, 1.0, ..., 133.0, 360.0, 0.0]], dtype=object)

In [13]:
y

array(['Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y',
       'Y', 'Y', 'N', 'Y', 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y',
       'N', 'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N',
       'N', 'N', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', 'N',
       'N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y',
       'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', 'Y', 'Y',
       'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N',
       'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'N

**Encoding the independent variable**

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:
y

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

**Splitting the dataset**

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,

**Feature Scaling**

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 11:] = sc.fit_transform(x_train[:, 11:])

In [19]:
x_test[:, 11:] = sc.transform(x_test[:, 11:])

**Logistic Regression**

In [20]:
from sklearn.linear_model import LogisticRegression
lr_classifier = LogisticRegression(random_state = 0)
lr_classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [21]:
lr_y_pred = lr_classifier.predict(x_test)

In [22]:
print(np.concatenate((lr_y_pred.reshape(len(lr_y_pred), 1),
                     y_test.reshape(len(y_test), 1)), 1))

[[1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]]


**Confusion Matrix and Accuracy**

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, lr_y_pred)
print(cm)
accuracy_score(y_test, lr_y_pred)

[[15 18]
 [ 2 88]]


0.8373983739837398

**K - Nearest Neighbors**

In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
knn_classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=15)

In [25]:
knn_y_pred = knn_classifier.predict(x_test)
print(np.concatenate((knn_y_pred.reshape(len(knn_y_pred), 1),
                     y_test.reshape(len(y_test), 1)), 1))

[[1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]]


**Confusion Matrix and Accuracy**

In [26]:
cm = confusion_matrix(y_test, knn_y_pred)
print(cm)
accuracy_score(y_test, knn_y_pred)

[[15 18]
 [ 2 88]]


0.8373983739837398

In [27]:
test_dataset = pd.read_csv('/kaggle/input/home-loan-approval/loan_sanction_test.csv')

In [28]:
test_dataset.info

<bound method DataFrame.info of       Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001015   Male     Yes          0      Graduate            No   
1    LP001022   Male     Yes          1      Graduate            No   
2    LP001031   Male     Yes          2      Graduate            No   
3    LP001035   Male     Yes          2      Graduate            No   
4    LP001051   Male      No          0  Not Graduate            No   
..        ...    ...     ...        ...           ...           ...   
362  LP002971   Male     Yes         3+  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0   

In [29]:
columns_to_drop = ['Loan_ID', 'Dependents']
numerical_features = test_dataset.drop(columns_to_drop, axis = 1).select_dtypes(include = ['number']).columns.tolist()
categorical_features = test_dataset.drop(columns_to_drop, axis = 1).select_dtypes(exclude = ['number']).columns.tolist()

In [30]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(test_dataset[numerical_features])
test_dataset[numerical_features] = imputer.transform(test_dataset[numerical_features])

In [31]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer.fit(test_dataset[categorical_features])
test_dataset[categorical_features] = imputer.transform(test_dataset[categorical_features])

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), categorical_features)], remainder = 'passthrough')
test_dataset = ct.fit_transform(test_dataset)

In [33]:

# Convert the transformed dataset back to a DataFrame
test_dataset = pd.DataFrame(test_dataset)

# Print the first few rows of the transformed DataFrame
print(test_dataset.head())

    0    1    2    3    4    5    6    7    8    9    10        11 12      13  \
0  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  LP001015  0  5720.0   
1  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  LP001022  1  3076.0   
2  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  LP001031  2  5000.0   
3  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  LP001035  2  2340.0   
4  0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  LP001051  0  3276.0   

       14     15     16        17  
0     0.0  110.0  360.0       1.0  
1  1500.0  126.0  360.0       1.0  
2  1800.0  208.0  360.0       1.0  
3  2546.0  100.0  360.0  0.825444  
4     0.0   78.0  360.0       1.0  


In [34]:
X_test = test_dataset.iloc[:, [0] + list(range(1, 11)) + list(range(13, test_dataset.shape[1]))].values

In [35]:
X_test[:, 11:] = sc.fit_transform(X_test[:, 11:])

In [36]:
lr_test_pred = lr_classifier.predict(X_test)

In [37]:
knn_test_pred = knn_classifier.predict(X_test)