<a href="https://www.kaggle.com/code/raghavs21/titanic-prediction?scriptVersionId=135425516" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

**Importing the Libraries**

In [1]:
import numpy as np
import pandas as pd

In [2]:
train_data = pd.read_csv('/kaggle/input/titanic/train.csv')

In [3]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
train_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [5]:
columns_to_drop = ['PassengerId', 'Name', 'Ticket', 'Survived', 'Cabin']
numerical_features = train_data.drop(columns_to_drop, axis = 1).select_dtypes(include = ['number']).columns.tolist()
categorical_features = train_data.drop(columns_to_drop, axis = 1).select_dtypes(exclude = ['number']).columns.tolist()

In [6]:
numerical_features

['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [7]:
categorical_features

['Sex', 'Embarked']

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(train_data[numerical_features])
train_data[numerical_features] = imputer.transform(train_data[numerical_features])

In [9]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer.fit(train_data[categorical_features])
train_data[categorical_features] = imputer.transform(train_data[categorical_features])

In [10]:
y = train_data.iloc[:, 1].values

In [11]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [12]:
train_data = train_data.drop('Survived', axis=1)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), categorical_features)], remainder = 'passthrough')
train_data = ct.fit_transform(train_data)

In [14]:
# Convert the transformed dataset back to a DataFrame
train_data = pd.DataFrame(train_data)

# Print the first few rows of the transformed DataFrame
print(train_data.head())

    0    1    2    3    4  5    6   \
0  0.0  1.0  0.0  0.0  1.0  1  3.0   
1  1.0  0.0  1.0  0.0  0.0  2  1.0   
2  1.0  0.0  0.0  0.0  1.0  3  3.0   
3  1.0  0.0  0.0  0.0  1.0  4  1.0   
4  0.0  1.0  0.0  0.0  1.0  5  3.0   

                                                  7     8    9    10  \
0                            Braund, Mr. Owen Harris  22.0  1.0  0.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  1.0  0.0   
2                             Heikkinen, Miss. Laina  26.0  0.0  0.0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  1.0  0.0   
4                           Allen, Mr. William Henry  35.0  0.0  0.0   

                 11       12    13  
0         A/5 21171     7.25   NaN  
1          PC 17599  71.2833   C85  
2  STON/O2. 3101282    7.925   NaN  
3            113803     53.1  C123  
4            373450     8.05   NaN  


In [15]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       891 non-null    object
 1   1       891 non-null    object
 2   2       891 non-null    object
 3   3       891 non-null    object
 4   4       891 non-null    object
 5   5       891 non-null    object
 6   6       891 non-null    object
 7   7       891 non-null    object
 8   8       891 non-null    object
 9   9       891 non-null    object
 10  10      891 non-null    object
 11  11      891 non-null    object
 12  12      891 non-null    object
 13  13      204 non-null    object
dtypes: object(14)
memory usage: 97.6+ KB


In [16]:
X = train_data.iloc[:, [0] + list(range(1, 7)) + list(range(8, 11)) + [12]].values

In [17]:
X

array([[0.0, 1.0, 0.0, ..., 1.0, 0.0, 7.25],
       [1.0, 0.0, 1.0, ..., 1.0, 0.0, 71.2833],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 7.925],
       ...,
       [1.0, 0.0, 0.0, ..., 1.0, 2.0, 23.45],
       [0.0, 1.0, 1.0, ..., 0.0, 0.0, 30.0],
       [0.0, 1.0, 0.0, ..., 0.0, 0.0, 7.75]], dtype=object)

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
columns_to_scale = [5, 6, 7, 10]
x_train[:,columns_to_scale] = sc.fit_transform(x_train[:,columns_to_scale])

In [20]:
x_test[:,columns_to_scale] = sc.transform(x_test[:,columns_to_scale])

In [21]:
x_train

array([[1.0, 0.0, 1.0, ..., 0.0, 2.0, -0.33167904332563686],
       [0.0, 1.0, 0.0, ..., 0.0, 0.0, -0.426405420419126],
       [0.0, 1.0, 1.0, ..., 1.0, 1.0, 0.10261957931985502],
       ...,
       [0.0, 1.0, 0.0, ..., 0.0, 0.0, -0.4816288743161627],
       [1.0, 0.0, 0.0, ..., 1.0, 0.0, -0.2886811164145166],
       [0.0, 1.0, 0.0, ..., 1.0, 1.0, 0.14245583525208688]], dtype=object)

In [22]:
from sklearn.linear_model import LogisticRegression
lr_classifier = LogisticRegression(random_state = 1)
lr_classifier.fit(x_train, y_train)

LogisticRegression(random_state=1)

In [23]:
lr_y_pred = lr_classifier.predict(x_test)

In [24]:
print(np.concatenate((lr_y_pred.reshape(len(lr_y_pred), 1),
                     y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, lr_y_pred)
print(cm)
accuracy_score(y_test, lr_y_pred)

[[92 18]
 [18 51]]


0.7988826815642458

In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
knn_classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [27]:
knn_y_pred = knn_classifier.predict(x_test)
print(np.concatenate((knn_y_pred.reshape(len(knn_y_pred), 1),
                     y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]

In [28]:
cm = confusion_matrix(y_test, knn_y_pred)
print(cm)
accuracy_score(y_test, knn_y_pred)


[[102   8]
 [ 24  45]]


0.8212290502793296

In [29]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel = 'linear', random_state = 1)
svm_classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=1)

In [30]:
svm_y_pred = svm_classifier.predict(x_test)
print(np.concatenate((svm_y_pred.reshape(len(svm_y_pred), 1),
                     y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]

In [31]:
cm = confusion_matrix(y_test, svm_y_pred)
print(cm)
accuracy_score(y_test, svm_y_pred)

[[92 18]
 [20 49]]


0.7877094972067039

In [32]:
from sklearn.svm import SVC
ksvm_classifier = SVC(kernel = 'rbf', random_state = 1)
ksvm_classifier.fit(x_train, y_train)

SVC(random_state=1)

In [33]:
ksvm_y_pred = ksvm_classifier.predict(x_test)
print(np.concatenate((ksvm_y_pred.reshape(len(ksvm_y_pred), 1),
                     y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]

In [34]:
cm = confusion_matrix(y_test, ksvm_y_pred)
print(cm)
accuracy_score(y_test, ksvm_y_pred)

[[96 14]
 [21 48]]


0.8044692737430168

In [35]:
from xgboost import XGBClassifier
xgb_classifier = XGBClassifier()
xgb_classifier.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [36]:
xgb_y_pred = xgb_classifier.predict(x_test)
print(np.concatenate((xgb_y_pred.reshape(len(xgb_y_pred), 1),
                     y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]

In [37]:
cm = confusion_matrix(y_test, xgb_y_pred)
print(cm)
accuracy_score(y_test, xgb_y_pred)

[[102   8]
 [ 18  51]]


0.8547486033519553

In [38]:
test_data = pd.read_csv('/kaggle/input/titanic/test.csv')

In [39]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [40]:
passenger_id = test_data['PassengerId']

In [41]:
columns_to_drop = ['PassengerId', 'Name', 'Ticket', 'Cabin']
numerical_features = test_data.drop(columns_to_drop, axis = 1).select_dtypes(include = ['number']).columns.tolist()
categorical_features = test_data.drop(columns_to_drop, axis = 1).select_dtypes(exclude = ['number']).columns.tolist()

In [42]:
categorical_features

['Sex', 'Embarked']

In [43]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(test_data[numerical_features])
test_data[numerical_features] = imputer.transform(test_data[numerical_features])

imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer.fit(test_data[categorical_features])
test_data[categorical_features] = imputer.transform(test_data[categorical_features])

In [44]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    float64
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    float64
 6   Parch        418 non-null    float64
 7   Ticket       418 non-null    object 
 8   Fare         418 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(5), int64(1), object(5)
memory usage: 36.0+ KB


In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), categorical_features)], remainder = 'passthrough')
test_data = ct.fit_transform(test_data)

In [46]:
# Convert the transformed dataset back to a DataFrame
test_data = pd.DataFrame(test_data)

# Print the first few rows of the transformed DataFrame
print(test_data.head())

    0    1    2    3    4    5    6   \
0  0.0  1.0  0.0  1.0  0.0  892  3.0   
1  1.0  0.0  0.0  0.0  1.0  893  3.0   
2  0.0  1.0  0.0  1.0  0.0  894  2.0   
3  0.0  1.0  0.0  0.0  1.0  895  3.0   
4  1.0  0.0  0.0  0.0  1.0  896  3.0   

                                             7     8    9    10       11  \
0                              Kelly, Mr. James  34.5  0.0  0.0   330911   
1              Wilkes, Mrs. James (Ellen Needs)  47.0  1.0  0.0   363272   
2                     Myles, Mr. Thomas Francis  62.0  0.0  0.0   240276   
3                              Wirz, Mr. Albert  27.0  0.0  0.0   315154   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.0  1.0  1.0  3101298   

        12   13  
0   7.8292  NaN  
1      7.0  NaN  
2   9.6875  NaN  
3   8.6625  NaN  
4  12.2875  NaN  


In [47]:
X_test = test_data.iloc[:, [0] + list(range(1, 7)) + list(range(8, 11)) + [12]].values

In [48]:
X_test

array([[0.0, 1.0, 0.0, ..., 0.0, 0.0, 7.8292],
       [1.0, 0.0, 0.0, ..., 1.0, 0.0, 7.0],
       [0.0, 1.0, 0.0, ..., 0.0, 0.0, 9.6875],
       ...,
       [0.0, 1.0, 0.0, ..., 0.0, 0.0, 7.25],
       [0.0, 1.0, 0.0, ..., 0.0, 0.0, 8.05],
       [0.0, 1.0, 1.0, ..., 1.0, 1.0, 22.3583]], dtype=object)

In [49]:
columns_to_scale = [5, 6, 7, 10]
X_test[:,columns_to_scale] = sc.transform(X_test[:,columns_to_scale])

In [50]:
lr_test_pred = lr_classifier.predict(X_test)

In [51]:
knn_test_pred = knn_classifier.predict(X_test)

In [52]:
svm_test_pred = svm_classifier.predict(X_test)

In [53]:
ksvm_test_pred = ksvm_classifier.predict(X_test)

In [54]:
xgb_test_pred = xgb_classifier.predict(X_test)

In [55]:
submission_df = pd.DataFrame({'PassengerId': passenger_id, 'Survived': xgb_test_pred})

In [56]:
submission_df

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [57]:
submission_df.to_csv('submission.csv', index=False)